name: CI

on:
  push:
    branches:
    - master

jobs:
  split-upm:
    name: update upm branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: update upm branch
      run: |
        echo '### head info'
        git log -1
        echo '### copy samples'
        cp -R "$SAMPLE_SOURCE" "$SAMPLE_DEST"
        echo '### split upm branch'
        git subtree split -P "$PKG_ROOT" -b upm
        echo '### update remote upm branch'
        git add -A
        git commit -m "CopySamples"
        git push origin upm
      env:
        PKG_ROOT: Packages/LocusBundleSystem
        SAMPLE_SOURCE: Assets/Sample
        SAMPLE_DEST: Packages/LocusBundleSystem/Samples~
