name: CI

on:
  push:
    tags:
    - '*'

jobs:
  split-upm:
    name: update upm branch
    runs-on: ubuntu-latest
    if: github.event.base_ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: update upm branch
      run: |
        echo '### head info'
        git log -1
        echo '### set git user info'
        git config user.email "locus84@gmail.com"
        git config user.name "automation"
        echo "## replacing version ${GITHUB_REF##*/}"
        sed -ie 's|\(\"version"\): "\(.*\)"|\1: '"\"${GITHUB_REF##*/}\"|" $PACKAGE_MANIFEST
        git add -A
        git commit -m "tagging version"
        git branch
        git push
        echo '### copy samples'
        cp -R "$SAMPLE_SOURCE" "$SAMPLE_DEST"
        git add -A
        git commit -m "CopySamples"
        echo '### split upm branch'
        git subtree split -P "$PKG_ROOT" -b upm
        echo '### update remote upm branch'
        git push -f origin upm
      env:
        PKG_ROOT: Packages/LocusBundleSystem
        SAMPLE_SOURCE: Assets/Sample
        SAMPLE_DEST: Packages/LocusBundleSystem/Samples~
        PACKAGE_MANIFEST: Packages/LocusBundleSystem/package.json
